wallet/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path('', RedirectView.as_view(url='transactions/create/', permanent=True)),
    # path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('transactions/', include('transactions.urls')),
    path('categories/', include('categories.urls')),
    path('budgets/', include('budgets.urls')),
]

transactions/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.contrib.auth import get_user_model
from categories.models import Category


class Transaction(models.Model):
    INCOME = 'income'
    EXPENSE = 'expense'

    TRANSACTION_TYPES = [
        (INCOME, 'Prihod'),
        (EXPENSE, 'Trošak'),
    ]

    transaction_type = models.CharField(max_length=7, choices=TRANSACTION_TYPES, default=EXPENSE)
    category = models.ForeignKey(Category, related_name='transactions', on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=255, blank=True)
    amount = models.DecimalField(max_digits=8, decimal_places=2, validators=[MinValueValidator(0.01)])
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    is_agency_related = models.BooleanField(default=False)  # Means that it's related to 'Web Victory'
    is_fixed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    is_deleted = models.BooleanField(default=False)

    @property
    def type_sign(self):
        return '+' if self.transaction_type == self.INCOME else '-'

    @property
    def full_category_str(self):
        if not self.category:
            return ''
        return str(self.category)

    def __str__(self):
        return f'{self.type_sign}{str(self.amount)} {self.title}'

budgets/forms.py
from django import forms
from django_select2.forms import Select2Widget
from categories.models import Category
from .models import Budget


class BudgetForm(forms.ModelForm):
    category = forms.ModelChoiceField(
        queryset=Category.objects.select_related('category_group').all(),
        widget=Select2Widget,
        label="Kategorija"
    )

    class Meta:
        model = Budget
        fields = ['category', 'start_date', 'end_date', 'amount', 'description']
        widgets = {
            'amount': forms.NumberInput(attrs={
                'inputmode': 'numeric',
                'style': 'appearance: none; -moz-appearance: textfield;',
            }),
            'start_date': forms.DateInput(attrs={
                'type': 'text',
                'class': 'form-control datepicker',
                'placeholder': 'YYYY-MM-DD',
            }),
            'end_date': forms.DateInput(attrs={
                'type': 'text',
                'class': 'form-control datepicker',
                'placeholder': 'YYYY-MM-DD',
            })
        }
        labels = {
            'amount': 'Iznos',
            'start_date': 'Početni Datum',
            'end_date': 'Krajnji Datum',
            'description': 'Opis',
        }

templates/base.html
{% load static %}

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
        <link rel="icon" sizes="16x16" href="{% static 'images/favicon-16x16.png' %}">
        <link rel="icon" sizes="32x32" href="{% static 'images/favicon-32x32.png' %}">
        <link rel="apple-touch-icon" sizes="57x57" href="{% static 'images/apple-touch-icon.png' %}">
        <link rel="icon" sizes="192x192" href="{% static 'images/android-chrome-192x192.png' %}">
        <link rel="icon" sizes="512x512" href="{% static 'images/android-chrome-512x512.png' %}">
        <title>{% block title %}Novčanik{% endblock %}</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
        {% block style %}{% endblock %}
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'transaction_overview' %}">Novčanik</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'transaction_create' %}">Nova transakcija</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'transaction_overview' %}">Transakcije</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'transaction_overview' %}?show=chart">Grafikon rashoda</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'budget_create' %}">Novi budžet</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'budget_list' %}">Budžeti</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'logout' %}">Izlogujte se</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'login' %}">Ulogujte se</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container" style="margin-top: 30px;">
            {% block content %}
            {% endblock %}
        </div>

        <script>
            $(document).ready(function() {
                $('.datepicker').datepicker({
                    format: 'yyyy-mm-dd',
                    autoclose: true,
                    todayHighlight: true,
                    weekStart: 1,
                    orientation: 'bottom'
                });

                $('#id_category').select2();
                $('#id_category').on('change', function() {
                    let selectedText = $("#id_category option:selected").text().trim().toLowerCase();
                    if (selectedText.includes("nabavka")) {
                        $("#id_is_fixed").prop("checked", true);
                    } else {
                        $("#id_is_fixed").prop("checked", false);
                    }
                });

                $("#id_title").autocomplete({
                    source: function(request, response) {
                        $.ajax({
                            url: "{% url 'title_suggestions' %}",
                            data: {
                                'title': request.term
                            },
                            success: function(data) {
                                data.sort(function(a, b) {
                                    return a.label.length - b.label.length;
                                });
                                response(data);
                            }
                        });
                    },
                    minLength: 4,
                    select: function(event, ui) {
                        $('#id_transaction_type').val(ui.item.transaction_type);
                        $('#id_category').val(ui.item.category).trigger('change');
                        $('#id_is_agency_related').prop('checked', ui.item.is_agency_related);
                        $('#id_is_fixed').prop('checked', ui.item.is_fixed);
                    }
                });
            });
        </script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
        <script>
            {% block script %}
                console.log('Default JS code');
            {% endblock %}
        </script>
    </body>
</html>

templates/login.html
{% extends "base.html" %}

{% block content %}

<div class="row">
    <div class="col-md-12">
        <form method="post" action="{% url 'login' %}" class="basic-form">
            <h2>Ulogujte se</h2>
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Nastavi</button>
        </form>
    </div>
</div>

{% endblock %}